<a href="https://colab.research.google.com/github/ojaspaul123/ML-Experiments/blob/main/Intros/Data_Inputation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [14]:
from google.colab import files
uploaded = files.upload()
df = pd.read_csv('Raw_Data.csv')
df.head()

Saving Raw_Data.csv to Raw_Data (1).csv

   Unnamed: 0    A    B    C    D
0           0  1.0  NaN  1.0  1.0
1           1  2.0  2.0  2.0  2.0
2           2  3.0  3.0  NaN  3.0
3           3  NaN  2.0  4.0  4.0
4           4  5.0  5.0  5.0  NaN

In [4]:
df.isnull().sum()

Unnamed: 0    0
A             2
B             2
C             2
D             1
dtype: int64

In [21]:
%%markdown
---
SIMPLE IMPUTER

---
SIMPLE IMPUTER

In [18]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy=  'mean')
df['A'] = imputer.fit_transform(df[['A']])

In [10]:
df.isnull().sum()

Unnamed: 0    0
A             0
B             2
C             2
D             1
dtype: int64

In [19]:
imputer1 = SimpleImputer(strategy='median')
df['B'] = imputer1.fit_transform(df[['B']])
df

   Unnamed: 0      A    B    C     D
0           0  1.000  3.0  1.0   1.0
1           1  2.000  2.0  2.0   2.0
2           2  3.000  3.0  NaN   3.0
3           3  4.625  2.0  4.0   4.0
4           4  5.000  5.0  5.0   NaN
5           5  6.000  6.0  NaN   6.0
6           6  3.000  3.0  3.0   7.0
7           7  4.625  3.0  4.0   8.0
8           8  8.000  3.0  4.0   9.0
9           9  9.000  9.0  9.0  10.0

In [20]:
imputer2 = SimpleImputer(strategy='most_frequent')
df['C'] = imputer2.fit_transform(df[['C']])
df

   Unnamed: 0      A    B    C     D
0           0  1.000  3.0  1.0   1.0
1           1  2.000  2.0  2.0   2.0
2           2  3.000  3.0  4.0   3.0
3           3  4.625  2.0  4.0   4.0
4           4  5.000  5.0  5.0   NaN
5           5  6.000  6.0  4.0   6.0
6           6  3.000  3.0  3.0   7.0
7           7  4.625  3.0  4.0   8.0
8           8  8.000  3.0  4.0   9.0
9           9  9.000  9.0  9.0  10.0

In [17]:
# User-input values
df.fillna(0)

   Unnamed: 0    A    B    C     D
0           0  1.0  0.0  1.0   1.0
1           1  2.0  2.0  2.0   2.0
2           2  3.0  3.0  0.0   3.0
3           3  0.0  2.0  4.0   4.0
4           4  5.0  5.0  5.0   0.0
5           5  6.0  6.0  0.0   6.0
6           6  3.0  3.0  3.0   7.0
7           7  0.0  3.0  4.0   8.0
8           8  8.0  0.0  4.0   9.0
9           9  9.0  9.0  9.0  10.0