<a href="https://colab.research.google.com/github/ojaspaul123/ML-Experiments/blob/main/Intros/Train_Test_Split.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%%markdown
---
Train_Test_Split

---
Train_Test_Split

In [2]:
import pandas as pd

from google.colab import files
uploaded = files.upload()
df = pd.read_csv('turtle_store.csv')
# Display the first few rows of the dataset
df.head()

Saving turtle_store.csv to turtle_store.csv

,Order ID,Brand,Product Name,Category,Size,Color,Quantity,Unit Price,Total Sales,Sale Date,Store Location
0,1001,Turtle & Co,Classic Logo Tee,Shirts,M,Green,3,19.99,59.97,2026-01-05,New York
1,1002,Shell Style,Graphic Turtle Shirt,Shirts,L,Blue,2,24.99,49.98,2026-01-07,Los Angeles
2,1003,Turtle & Co,Slim Fit Chinos,Pants,32,Khaki,4,39.99,159.96,2026-01-10,Chicago
3,1004,Ocean Threads,Relaxed Cargo Pants,Pants,34,Olive,2,44.99,89.98,2026-01-12,Houston
4,1005,Shell Style,Polo Shirt,Shirts,S,White,5,29.99,149.95,2026-01-15,Phoenix

In [3]:
X = df.drop('Category',axis=1)
y = df['Category']

In [4]:
X.shape

(20, 10)

In [5]:
y.shape

(20,)

In [6]:
df.iloc[:,]

,Order ID,Brand,Product Name,Category,Size,Color,Quantity,Unit Price,Total Sales,Sale Date,Store Location
0,1001,Turtle & Co,Classic Logo Tee,Shirts,M,Green,3,19.99,59.97,2026-01-05,New York
1,1002,Shell Style,Graphic Turtle Shirt,Shirts,L,Blue,2,24.99,49.98,2026-01-07,Los Angeles
2,1003,Turtle & Co,Slim Fit Chinos,Pants,32,Khaki,4,39.99,159.96,2026-01-10,Chicago
3,1004,Ocean Threads,Relaxed Cargo Pants,Pants,34,Olive,2,44.99,89.98,2026-01-12,Houston
4,1005,Shell Style,Polo Shirt,Shirts,S,White,5,29.99,149.95,2026-01-15,Phoenix
5,1006,Turtle & Co,Jogger Pants,Pants,M,Black,3,34.99,104.97,2026-01-18,New York
6,1007,Ocean Threads,V-Neck Turtle Tee,Shirts,XL,Navy,2,22.99,45.98,2026-01-20,Los Angeles
7,1008,Shell Style,Straight Leg Jeans,Pants,30,Dark Blue,4,49.99,199.96,2026-01-22,Chicago
8,1009,Turtle & Co,Henley Long Sleeve Shirt,Shirts,M,Grey,3,27.99,83.97,2026-01-25,Houston
9,1010,Reef Wear,Linen Pants,Pants,36,Beige,2,54.99,109.98,2026-01-28,Phoenix
10,1011,Ocean Threads,Striped Button-Down Shirt,Shirts,L,Blue/White,5,34.99,174.95,2026-02-01,New York
11,1012,Reef Wear,Athletic Track Pants,Pants,M,Black,6,29.99,179.94,2026-02-04,Los Angeles
12,1013,Shell Style,Oversized Tee,Shirts,XL,Yellow,4,21.99,87.96,2026-02-06,Chicago
13,1014,Turtle & Co,Slim Fit Dress Pants,Pants,32,Charcoal,2,59.99,119.98,2026-02-09,Houston
14,1015,Reef Wear,Flannel Shirt,Shirts,S,Red/Black,3,32.99,98.97,2026-02-12,Phoenix
15,1016,Ocean Threads,Cropped Wide Leg Pants,Pants,28,White,4,44.99,179.96,2026-02-15,New York
16,1017,Shell Style,Tie-Dye Shirt,Shirts,M,Multicolor,5,26.99,134.95,2026-02-18,Los Angeles
17,1018,Turtle & Co,Corduroy Pants,Pants,34,Brown,3,49.99,149.97,2026-02-20,Chicago
18,1019,Reef Wear,Sleeveless Tank Top,Shirts,L,Black,6,14.99,89.94,2026-02-22,Houston
19,1020,Ocean Threads,Pleated Trousers,Pants,32,Tan,2,54.99,109.98,2026-02-25,Phoenix

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [9]:
X_train.shape

(16, 10)

In [10]:
X_test.shape

(4, 10)

In [11]:
y_train.shape

(16,)

In [12]:
y_test.shape

(4,)